name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Step 2: Setup Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt || true

    # Step 4: Run Unit Tests
    - name: Run Unit Tests
      run: pytest -v

    # Step 5: Build Docker Image (optional check before Render does it)
    - name: Build Docker Image
      run: docker build -t myapp:latest .

    # Step 6: Trigger Render Deploy
    - name: Deploy to Render
      run: |
        curl -X POST "https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys" \
        -H "Accept: application/json" \
        -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}"
